export const enum EIcons {
  Phone = "phone",
  Email = "email",
  Lock = "lock",
  Eye = "eye",
  CloseEye = "close-eye",
  Close = "close",
  Upload = "upload",
  Home = "home",
  Card = "card",
  Arrow = "arrow",
  Wallet = "wallet",
  Search = "search",
  User = "user",
}
